### ISSUE TITLE
Possible error when pushing my code

### ISSUE THREAD

**Issue by D-H-S** [foxdye96/stackoverflow#4]
When pushing my code the video I follow showed me how to push by pushing using master or whatever it is called and It says I edited the other two files that were in the css folder but I didnt change anything at the same time my css file is not showing up for me so I am not sure what exactly I did wrong.

**Comment by foxdye96** [comment]
lol what. did u pull the changes first and then push? 

Dont use the dumb command line if youre using it. Use a GUI like GitHub desktop

**Comment by haytham5** [comment]
yes, you should definitely use a GUI. For now, send me your code and I'll push it for you
